# Generated by Django 4.2.6 on 2023-10-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('pleasant_habit', models.CharField(blank=True, max_length=100, null=True, verbose_name='приятная привычка')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='периодичность')),
                ('reward', models.CharField(max_length=100, verbose_name='вознаграждение')),
                ('execution_time', models.TimeField(verbose_name='время выполнения')),
                ('is_publish', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('binding_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]