# Generated by Django 4.2.6 on 2023-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_pleasant_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение'),
        ),
    ]