# Generated by Django 4.2.6 on 2023-10-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegram_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'телеграм', 'verbose_name_plural': 'телеграмы'},
        ),
    ]